### ISSUE TITLE
ADR: xAPI Transform Tech Selection

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-oars#22]

**Comment by pomegranited** [comment]
@bmtcril Semi-related to https://github.com/openedx/openedx-oars/issues/12 -- you and @jmaupetit started discussing at the [2023-1-11 Data Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3627909121/Data+WG+2023-01-11+Meeting+notes) meeting the possibility of splitting out Ralph's xAPI transforms from the LRS functionality it provides.

This idea fits well with the "modular reference system" approach that OARS is taking, since people may love Ralph's xAPI schemas and transforms, but want to use a different LRS for the actual storage. Has this been discussed more anywhere?

**Comment by bmtcril** [comment]
As it stands I believe Ralph can be used as a command line tool without standing up the LRS, though I think there's work to be done on being able to support older / more events (old course identifiers, differently / poorly formed events etc). There's also work to figure out how event replay will find the actor identifier since it's not running in the LMS context and tracking logs usually only have integer user id or username.

We discussed breaking out the transforms in this meeting, but are trying to find consensus on what implementation to use. The main use case is making sure that any "real time" statements sent by event-routing-backends from the LMS will exactly match what Ralph would generate on an tracking log replay. I'm hoping to have a decision there in less than a week.

**Comment by bmtcril** [comment]
https://github.com/openedx/openedx-oars/blob/main/docs/decisions/0002_xapi.rst
