### ISSUE TITLE
Superset: Fetch superuser/staff status from OAuth

### ISSUE THREAD

**Issue by pomegranited** [openedx/openedx-oars#42]
Currently, the [Open edX SSO Security Manager](https://github.com/openedx/tutor-contrib-superset/blob/main/tutorsuperset/templates/superset/apps/pythonpath/openedx_sso_security_manager.py) installed by https://github.com/openedx/tutor-contrib-superset queries the Open edX MySQL database to determine if a user is a superuser or global staff, in order to determine their roles and permissions in Superset.

This information should be gleaned from OAuth data instead.
e.g. the [openedx:auth_backends/backends.py](https://github.com/openedx/auth-backends/blob/d0ad4d7912c8ae70608bdc8f6e1a0d070d8cd520/auth_backends/backends.py#L100-L106) decodes this information from the JWT access_token. Superset has only an OAuth2 bearer token, but we should be able to convert this to JWT ([ref](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/oauth_dispatch/docs/decisions/0003-use-jwt-as-oauth-tokens-remove-openid-connect.rst#requesting-jwt-tokens)).

cf https://github.com/openedx/tutor-contrib-superset/pull/6#discussion_r1127369597

**Comment by pomegranited** [comment]
FYI @bmtcril

**Comment by bmtcril** [comment]
We may be able to fix this one in the same changes as well: https://github.com/openedx/tutor-contrib-superset/issues/11

**Comment by Ian2012** [comment]
Is there a defined starting point for this issue?

**Comment by pomegranited** [comment]
Hi @Ian2012 thanks for taking on this task!

I don't enough about OAuth2 and JWT to advise you specifically here, but maybe these pointers will help?

* Superset uses the Flask AppBuilder framework, and we're currently using authlib for SSO. Perhaps the docs for FAB or authlib will help describe how to make our [custom auth manager](https://github.com/openedx/tutor-contrib-superset/blob/main/tutorsuperset/templates/superset/apps/pythonpath/openedx_sso_security_manager.py) fetch JWT tokens? Or maybe there are other FAB projects that use JWT tokens during authentication?
* According to [these docs](https://openedx.atlassian.net/wiki/spaces/AC/pages/42599769/OAuth2+JWT+and+Mobile#OAuth2%2CJWTandMobile-OAuth2AccessToken%E2%86%92JWTtoken), you can hit the `/oauth2/access_token/` endpoint (again) with the access token received during SSO, and request a JWT access token. Those docs are old, but seem to be referencing code that was moved to [edx-platform/openedx/core/djangoapps/auth_exchange](https://github.com/openedx/edx-platform/tree/master/openedx/core/djangoapps/auth_exchange). But I'm not sure if our SSO use case fits the purpose of those auth views?

**Comment by Ian2012** [comment]
@pomegranited Seems like to get a JWT token, we need to authenticate with google or facebook, or send the username and password:

![image](https://user-images.githubusercontent.com/33465240/235156735-c9c71aea-d436-4de5-bcbb-c8d49034a00f.png)

**Comment by pomegranited** [comment]
@Ian2012 I'm hoping that comment is out of date..

Have you tried using [the `superset-sso` DOT application](https://github.com/openedx/tutor-contrib-superset/blob/main/tutorsuperset/templates/superset/jobs/init/init-openedx.sh#L3-L9) created during Superset init?

> http://localhost:8000/oauth2/exchange_access_token/superset-sso

Or even just `oauth2`, since it looks like the [view might just use the `client_id` to determine the DOT Application backend](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/oauth_dispatch/views.py#L26-L30) which is passed in as POST data?

> http://localhost:8000/oauth2/exchange_access_token/oauth2

**Comment by mariajgrimaldi** [comment]
Hi there @pomegranited: I ran some tests following your suggestions, thank you so much! Here are our findings:

We first tried `oauth2/exchange_access_token/superset-sso` as you suggested, but we got the following:
![supersetsso-missing](https://user-images.githubusercontent.com/64440265/235735666-6fdfbf71-5fbc-4db0-9a6d-c05d35df5c38.png)
After getting the missing backend error, we tried your other suggestion: `oauth2/exchange_access_token/oauth2`, getting the same result. These attempts led us to list the backends being used:
![get-backends](https://user-images.githubusercontent.com/64440265/235735754-faca27b7-99c6-47ac-a21c-7e91d7b3c01f.png)

The list has just authentication backends which we suppose are used to generate the new token, so my theory is that we need a working backend to be able to generate the token. I believe just a few backends like google and facebook are supported, as the docs say.

**Comment by mariajgrimaldi** [comment]
We tried other stuff, like getting the JWT cookie set during the LMS login, which worked: https://github.com/openedx/tutor-contrib-superset/pull/28. The main issue with this implementation is that for it to work, superset needs to be hosted in a subdomain of the LMS so they can share these types of cookies. 🤔

**Comment by pomegranited** [comment]
@mariajgrimaldi  Hmm.. that's probably an ok workaround if need be.. What do you think, @bmtcril ?

I dug around and didn't find anything specifically useful to this cause, but I found something kind of related: With python social_auth, there's also a [`user_details()`](https://github.com/python-social-auth/social-core/blob/master/social_core/pipeline/user.py#L76-L79) method in the auth pipeline which gets sent a bunch of extra user info. The details of what is in the `userinfo` field depends on the SSO provider, and the `scope` requested from (and granted by) that provider. I'm not sure what user data might be provided by Open edX SSO, but it might include the superuser/staff flags?

Flask-AppBuilder shows an example of its equivalent using OAuth: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/docs/security.rst#authentication-oauth

It shows example configs for various 3rd-party oauth providers , with an example of overwriting the `@appbuilder.sm.oauth_user_info_getter` method on the security manager class and fetching various extra user info fields like names and emails. We're currently [configuring the oauth app with only the `user_id` scope](https://github.com/openedx/tutor-contrib-superset/blob/main/tutorsuperset/templates/superset/jobs/init/init-openedx.sh#L8) -- but I think there's [`profile` and `email` scopes available](https://discuss.openedx.org/t/how-to-setup-oauth2-sso-using-auth-backends-plugin/1403/9?u=jill) too? I think you also need to request these same scopes during authentication, so would need to change the [OAUTH_PROVIDERS setting](https://github.com/openedx/tutor-contrib-superset/blob/main/tutorsuperset/templates/superset/apps/pythonpath/superset_config_docker.py#L40) to something like `"profile,email,user_id"`.  At the very least, this could replace [our hit to the `user_profile` URL made during authentication](https://github.com/openedx/tutor-contrib-superset/blob/main/tutorsuperset/templates/superset/apps/pythonpath/openedx_sso_security_manager.py#L29-L49).

**Comment by mariajgrimaldi** [comment]
@pomegranited: this is kind of a brain dump. Here we go:

### About JWT tokens and scopes

This is how I understand the current mechanism, let me know if I got something wrong:

- Superset uses the LMS as IdP with Oauth2 implemented by Django Oauth Toolkit
- I try login into superset
- Superset redirects to /oauth2/authorize using the client ID previously configured
- In the LMS, we search for the application with such client ID
- After finding it, DOT redirects to the `redirect uri` hosted by the Superset application: http://superset.local.overhang.io/oauth-authorized/openedxsso
- That authorization view generates a Bearer token
- After successfully generating the token, tries getting the users information and so on.

Now, if I'm right, the token generated doesn't contain information about the user. So, we could configure other scopes and still our token would have the same amount of data, right?. Now, If we were using JWT instead, we could modify the scopes getting that way more info about the user associated with the token, as explained [here](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/oauth_dispatch/docs/decisions/0003-use-jwt-as-oauth-tokens-remove-openid-connect.rst#jwt-token). 

This mechanism reminds me a bit of the Studio SSO, which roughly works as follows:

- Studio uses the LMS as IdP with Oauth2 implemented by Django Oauth Toolkit
- I try to login into Studio
- Studio redirects to the LMS path /oauth2/authorize using the client ID previously configured
- In the LMS, we search for the application with such client ID
- After finding it, DOT redirects to the `redirect uri` hosted by the Studio service: http://studio.local.overhang.io/complete/edx-oauth2/
- That authorization view generates a JWT token
- After successfully generating the token, tries getting the users information from the JWT token previously generated.

Studio uses the [auth-backend](https://github.com/openedx/auth-backends/) library to implement the callback in the redirect URI field. Calling `complete/edx-oauth2` triggers the authentication pipeline on the Studio side, which consists, among other things, of generating the JWT that is used afterward to get the user details: https://github.com/openedx/auth-backends/blob/e81015d45bf12de514045a135f0cc98fb69a42f3/auth_backends/backends.py#L108. This is just what we need! But there's a problem, while the authorization view edx-oauth2 backend gets an authorization code generated by the LMS and sent in some of the requests, our superset app doesn't:

Authorization view from the edx-oauth2 backend based on Social Core:

https://github.com/python-social-auth/social-core/blob/9ce53e7c3ea8ee7cccef714478f4601dce7f7be8/social_core/backends/oauth.py#L359

Authorization view from flask app builder:

https://github.com/dpgaspar/Flask-AppBuilder/blob/b82bb520f70bc726e5f199604bb2696fe3395e77/flask_appbuilder/security/views.py#L650

So that's why we can't just generate a JWT token instead of a Bearer one. Now, I'm not sure if we could do a workaround to get the authorization code to generate a JWT token though.

### About flask app builder auth

The pattern I've found in some examples for getting the user's information is calling an API hosted by the IdP, like when they do `self.appbuilder.sm.oauth_remotes[provider].get("userinfo")` and it means making an API call to the LMS getting: `"GET /userinfo HTTP/1.1" 404`. I don't think calling an API to get that kind of info would be a good idea security-wise 🤔 . Also, for that I don't think calling the profile API is a bad thing at all!

**Comment by pomegranited** [comment]
Hi @mariajgrimaldi , thank you for summarising what you've learned about OAuth and JWT, that really helps me understand!

I've CC'd you on this thread with @robrap [on Slack](https://openedx.slack.com/archives/C02QN50TYMD/p1683109787419959?thread_ts=1683091799.124999&cid=C02QN50TYMD) -- he's suggesting there's a way to request the token directly as JWT, bypassing Bearer tokens entirely.

> Also, that pattern makes me think that calling the profile API is not a bad thing at all!

Lol yeah, agreed. Please disregard my suggestion about changing how we get this info :)

**Comment by mariajgrimaldi** [comment]
@robrap: I'll research a bit more of that! I'll let you know

**Comment by robrap** [comment]
If this is interacting with our APIs, at this time, we require the authorization header to use `JWT` in place of `Bearer`. Not sure if this is configurable? https://github.com/lepture/authlib/blob/70a6bfa92aa1007515465a7af1a60a4518abe699/authlib/oauth2/auth.py#L80-L83

**Comment by mariajgrimaldi** [comment]
Well, we kind of did it: https://github.com/openedx/tutor-contrib-superset/pull/40/. I followed Robert's suggestion to get there:

- Override the `AuthorizationView` [from the superset application](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/views.py#L602), specifically the method `oauth_authorized` which exposes `/oauth-authorized/provider`. The idea of modifying the method was to change the token type from Bearer to JWT:
https://github.com/openedx/tutor-contrib-superset/pull/40/files#diff-86883c60f8e1c94fe60abff51337290ebb6d04e9fac49f8c6731d7613045f445R82
- Configure the sign methods to include JWT headers: https://github.com/openedx/tutor-contrib-superset/pull/40/files#diff-86883c60f8e1c94fe60abff51337290ebb6d04e9fac49f8c6731d7613045f445R142-R145
- Get the token correctly from the response: https://github.com/openedx/tutor-contrib-superset/pull/40/files#diff-86883c60f8e1c94fe60abff51337290ebb6d04e9fac49f8c6731d7613045f445R154

This is currently looking incredibly hacky, but it's working:

![image](https://github.com/openedx/openedx-oars/assets/64440265/0cc8c6f0-be61-496c-bd2a-0eed0bd4c873)
![image](https://github.com/openedx/openedx-oars/assets/64440265/daf7b624-de84-4441-8db1-248c0c7e394e)

I'm gonna do some other stuff and take a look later with fresher eyes.

**Comment by robrap** [comment]
@mariajgrimaldi: If we used "Bearer" in the Authorization header, rather than "JWT", but included the JWT as the token, would that be the non-hacky version? I think that would all be part of the BearerAuthentication DEPR: https://github.com/openedx/edx-drf-extensions/issues/284.

FYI: @feanil: Since you are looking into authentication clean-up work and issues related to current state.

**Comment by Ian2012** [comment]
There was no need to modify the OAuthView class to accept the JWT token type.

Here is a new implementation of this working: https://github.com/openedx/tutor-contrib-superset/pull/44 with some refactoring and fixes

**Comment by Ian2012** [comment]
assign me
